---
- name: Backup Cisco Router or Switch
  hosts: all
  connection: network_cli
  gather_facts: true
  vars_files:
    - vault.yml
  tasks:
    - name: Access Ansible net hostname
      ios_facts:
        gather_subset: all
    - name: Get current date
      local_action: command date +%Y-%b-%d
      register: date
    - name: Get current time
      local_action: command date +%H:%M
      register: time
    - name: Get running-config and save it
      ios_config:
       backup: yes
       backup_options:
         filename: "{{ ansible_net_hostname }}_{{ ansible_host }}.txt"
         dir_path: /home/aliansible/Documents/o/{{ date.stdout }}_at_{{ time.stdout }}
    - name: Tasks done
      debug: msg="All tasks have been done on {{ date.stdout }} at {{ time.stdout }}."
    - debug:
        msg: |-
          ansible_user: {{ ansible_user }}
          ansible_password: {{ ansible_password }}
